# Generated by Django 3.1.5 on 2021-08-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_string', models.CharField(max_length=50)),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_page', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_string', models.CharField(max_length=50)),
                ('provider_page', models.IntegerField(default=1)),
                ('provider_name', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoApiRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('low_url', models.URLField()),
                ('high_url', models.URLField()),
                ('thumbnail', models.CharField(default='', max_length=250)),
                ('is_save', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, upload_to='api_videos/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backgroundclip.videosearch')),
            ],
        ),
        migrations.CreateModel(
            name='ImageApiRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('low_url', models.URLField()),
                ('high_url', models.URLField()),
                ('is_save', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='api_images/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backgroundclip.imagesearch')),
            ],
        ),
    ]
