from django.contrib import admin

from newImageEditor.models import (
    ImageCreator,ImageCreatorGenerated
)
class ImageCreatorAdmin(admin.ModelAdmin):
    readonly_fields = ('timestamp','_uid',)
    list_filter = ("isGenerated","isPersonalized","isTemplate","isAutoGenerated","isDeleted")



admin.site.register(ImageCreator,ImageCreatorAdmin)
admin.site.register(ImageCreatorGenerated)

